### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by rayshan** [sto3psl/react-datawrapper-chart#4]
Since 1.0.4, create-react-app fails to build, with error `Module not found: Can't resolve 'react-datawrapper-chart' in xxx`. 1.0.3 worked fine.

Adding  `"main": "./pkg/dist-web/index.js",` to this package's `package.json` worked.

**Comment by aLotlBit** [comment]
You are a lifesaver!!! : )

**Comment by sto3psl** [comment]
Hi! Thanks for opening this issue. It turns out that I published version `1.0.4` the wrong way. I just created a new version `1.1.0` which fixes the problem. 

You can check it out in the updated Codesandbox example [Link](https://codesandbox.io/s/32y4937kq1?fontsize=14), which uses `create-react-app`. 

`npm i react-datawrapper-chart@1.1.0`
